apiVersion: v1
kind: Service
metadata:
  name: epic
  labels:
    app: epic
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: epic
